-- 033_stage_dates_staging_sheet.sql
--
-- Stage dates get a staging sheet of their own, and the dates already held
-- move onto it. Settled in full with the owner on 2026-09-11: DECISIONS.md,
-- "Each clean tab has a staging sheet of the same shape", "Stage 1 and Stage 2
-- completion dates, from the PhD", and "When two sources give the same stage
-- date, the more primary goes onto the clean sheet".
--
-- No date is added here. This moves the dates already held, so that the move
-- can be proved to have changed nothing before any PhD date is loaded.
--
-- What it does:
--   1. Hybrid Bills get the stage names they really had: Stage 1, 2 and 3.
--      db/018 gave them the Private Bill names. No Hybrid Bill is held yet.
--   2. The stage-dates staging sheet, stage_candidate.
--   3. The dates on bill_candidate move onto it: every passing date, and every
--      Stage 1 rejection date read from the Official Report, each with its
--      source, when it was read, and its line's review status. Session 1's are
--      stamped with the stage records already on the clean sheet, and are
--      checked to reproduce them exactly.
--   4. The clean sheet's one new rule: a stage completed on a date not known
--      must have a note.
--   5. The error checker reads the new sheet, and gains the agreed checks.
--   6. The two old columns come off bill_candidate.
--   7. The gaps list, v_stage_date_gaps.
--   8. Descriptions brought up to date, and methodology note M2 rewritten.
--
-- Everything it creates is given to legdata, so Postico can open it. So is
-- ref_bill_type_stage, which the error checker now reads: a migration had left
-- it belonging to the administrator, and a checker owned by legdata cannot read
-- a list legdata is refused.

BEGIN;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM bill_candidate
              WHERE end_stage_1_date IS NOT NULL
                AND outcome IS DISTINCT FROM 'rejected_stage_1') THEN
    RAISE EXCEPTION 'Refusing to run: a Stage 1 date sits on a line that was not rejected at Stage 1. This migration only knows how to move rejection dates.';
  END IF;
  IF EXISTS (SELECT 1 FROM bill WHERE bill_type = 'hybrid') THEN
    RAISE EXCEPTION 'Refusing to run: a Hybrid Bill is on the clean sheet with stage records under the old names.';
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 1. Hybrid Bills run Stage 1, 2 and 3
-- ---------------------------------------------------------------------------
--
-- The Parliament's page "About Hybrid Bills" (read 2026-09-11, copy in
-- sources/procedure/) calls them Stage 1, 2 and 3, and so does the record of
-- the Forth Crossing Bill, the only Hybrid Bill there has been.

UPDATE ref_bill_type_stage
   SET stage = CASE stage_order WHEN 1 THEN 'stage_1' WHEN 2 THEN 'stage_2' ELSE 'stage_3' END
 WHERE bill_type = 'hybrid' AND stage_order IN (1, 2, 3);

ALTER TABLE ref_bill_type_stage OWNER TO legdata;

COMMENT ON TABLE ref_bill_type_stage IS
 'Which stages belong to which kind of bill, and in what order. Five bill types times four positions: government, members, committee and hybrid bills run Stage 1, 2 and 3 then Reconsideration; private bills run Preliminary, Consideration and Final Stage then Reconsideration. (Hybrid bills had the private names until db/033; the Forth Crossing Bill ran Stage 1, 2 and 3.) A trigger on stage_event reads this table, so the database refuses a Stage 2 recorded against a Private Bill, or a Preliminary Stage against a Government Bill, or a real stage name at the wrong position. The error checker reads it for the stage-dates staging sheet.';

COMMENT ON TABLE ref_stage IS
 'The names stages actually have, covering both the Stage 1/2/3 sequence of public and Hybrid Bills and the Preliminary/Consideration/Final sequence of Private Bills. Every allowed value for stage_event.stage is a row here, with its own definition, so a value can be added or re-labelled without changing the schema and so each one carries the text explaining it to a reader.';

-- ---------------------------------------------------------------------------
-- 2. The stage-dates staging sheet
-- ---------------------------------------------------------------------------
--
-- The same shape as stage_event, plus the gate and the stamps bill_candidate
-- has. Permissive like bill_candidate: a bad value lands as a row that can be
-- looked at, and the error checker says what is wrong with it. The two things
-- enforced are that a row belongs to a staging line, and one row per stage per
-- source for each line.

CREATE TABLE stage_candidate (
    stage_candidate_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id            integer NOT NULL REFERENCES bill_candidate,
    stage                   text,
    stage_order             integer,
    date_completed          date,
    completed               boolean,
    fell_here               boolean,
    source                  text,
    source_ref              text,
    observed_at             date,
    note                    text,
    review_status           text NOT NULL DEFAULT 'new'
                            CHECK (review_status IN ('new', 'accepted', 'rejected', 'held')),
    review_note             text,
    reviewed_at             timestamptz,
    promoted_stage_event_id integer REFERENCES stage_event ON DELETE SET NULL,
    promoted_at             timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (candidate_id, stage_order, source)
);

ALTER TABLE stage_candidate OWNER TO legdata;

CREATE TRIGGER stage_candidate_touch
    BEFORE UPDATE ON stage_candidate
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

COMMENT ON TABLE stage_candidate IS
 'The stage-dates staging sheet: one row per stage of a bill, per source, waiting to be checked before it goes onto stage_event. Every stage date arrives here, whatever its source: a factsheet''s passing date when a session is loaded, a date read from the Official Report at review, a date from the owner''s PhD dataset. Each row belongs to a line of bill_candidate, which is its bill. Nothing reaches stage_event except from an accepted row here. Where two accepted rows give the same stage of the same bill, the error checker requires them to agree, and promotion carries the one from the more primary source: the Official Report, then a factsheet, then the PhD dataset. The other stays here as the check. Rows are kept permanently.';

COMMENT ON COLUMN stage_candidate.stage_candidate_id IS
 'Our identifier for this row. Not a bill number, and not carried onto stage_event.';
COMMENT ON COLUMN stage_candidate.candidate_id IS
 'Which staging line, and so which bill, this stage belongs to: rows for line 17 become stage records of bill 17. Required: a stage date cannot wait here without a bill line behind it.';
COMMENT ON COLUMN stage_candidate.stage IS
 'The stage''s real name for this kind of bill: Stage 1, 2 or 3 for a public or Hybrid Bill; Preliminary, Consideration or Final for a Private Bill; or Reconsideration. Should be a code from ref_stage, and the name ref_bill_type_stage gives for the line''s bill type at this position. Nothing in this table enforces either; the error checker flags both, and stage_event refuses a wrong one.';
COMMENT ON COLUMN stage_candidate.stage_order IS
 'Where the stage comes in its bill type''s sequence: 1, 2 or 3, or 4 for Reconsideration. Should match the stage''s name in ref_bill_type_stage; the error checker flags a mismatch.';
COMMENT ON COLUMN stage_candidate.date_completed IS
 'The date the stage was completed, at the points methodology note M2 sets out. On a stage the bill did not complete, the date of the decision that ended it where there was one, such as a Stage 1 rejection, and otherwise empty. On a completed stage, empty means completed on a date not known, and the note must say why. A stage not yet entered has no row at all.';
COMMENT ON COLUMN stage_candidate.completed IS
 'True if the bill got through this stage. False means it reached the stage and stopped there, or is still in it. Should always be filled; the error checker flags an empty one.';
COMMENT ON COLUMN stage_candidate.fell_here IS
 'True on the stage where a bill that did not pass ended: rejected, withdrawn, or fallen while in it. Never on a completed stage or on a bill that passed, and nothing may be recorded after it; the error checker flags each. Should always be filled.';
COMMENT ON COLUMN stage_candidate.source IS
 'Where this stage date came from: normally spice_factsheet, official_report or phd. Should be a code from ref_source. Nothing in this table enforces that, but stage_event.source does.';
COMMENT ON COLUMN stage_candidate.source_ref IS
 'The exact place within that source: which factsheet, the Official Report link, or the PhD dataset''s reference.';
COMMENT ON COLUMN stage_candidate.observed_at IS
 'The date the source was read. Should always be filled; the error checker flags an empty one.';
COMMENT ON COLUMN stage_candidate.note IS
 'Anything irregular about this stage that a reader should see, carried onto stage_event.note at promotion. Required for a stage completed on a date not known, to say why. Empty means nothing irregular.';
COMMENT ON COLUMN stage_candidate.review_status IS
 'The gate for this row: new (not looked at), accepted, rejected or held, as on bill_candidate. Rows arrive new, the owner''s own PhD dates included. Only accepted rows go onto stage_event, and a session is not promoted while any of its rows is new or held. Rows moved from bill_candidate by db/033 kept their line''s status. This is the one value in this table the database enforces.';
COMMENT ON COLUMN stage_candidate.review_note IS
 'What the reviewer decided about this row and why. Stays on this sheet. Empty means nothing needed saying.';
COMMENT ON COLUMN stage_candidate.reviewed_at IS
 'When a person reviewed this row. Empty means it has not been reviewed.';
COMMENT ON COLUMN stage_candidate.promoted_stage_event_id IS
 'Which stage_event row this became at the last promotion. Stage records are renumbered each time a session is put back, so this number is too. Empty means not promoted: not accepted, its session not on the clean sheet, or another accepted row for the same stage was carried instead.';
COMMENT ON COLUMN stage_candidate.promoted_at IS
 'When this row was last promoted. Empty means it is not on the clean sheet.';
COMMENT ON COLUMN stage_candidate.created_at IS
 'When this row was put on the sheet. Set automatically.';
COMMENT ON COLUMN stage_candidate.updated_at IS
 'When this row was last changed. Set automatically.';

-- ---------------------------------------------------------------------------
-- 3. Move the dates
-- ---------------------------------------------------------------------------
--
-- Exactly what promotion used to write from the two columns, so putting a
-- session back from this sheet gives the same stage records.

-- Passing dates, read off the factsheet: the third stage of the line's own
-- sequence, completed.
INSERT INTO stage_candidate (candidate_id, stage, stage_order, date_completed,
                             completed, fell_here, source, source_ref, observed_at,
                             review_status, reviewed_at)
SELECT c.candidate_id, s.stage, 3, c.end_stage_3_date, true, false,
       c.source, c.source_ref, c.observed_at, c.review_status, c.reviewed_at
  FROM bill_candidate c
  LEFT JOIN ref_bill_type_stage s ON s.bill_type = c.bill_type AND s.stage_order = 3
 WHERE c.end_stage_3_date IS NOT NULL
 ORDER BY c.candidate_id;

-- Stage 1 rejections, read from the Official Report: the first stage, not
-- completed, where the bill ended, dated by the decision. The citation is the
-- first link in the line's review note, and the date read is the line's
-- official_report_read_on.
INSERT INTO stage_candidate (candidate_id, stage, stage_order, date_completed,
                             completed, fell_here, source, source_ref, observed_at,
                             review_status, reviewed_at)
SELECT c.candidate_id, s.stage, 1, c.end_stage_1_date, false, true,
       'official_report', substring(c.review_note from 'https?://\S+'),
       c.official_report_read_on, c.review_status, c.reviewed_at
  FROM bill_candidate c
  LEFT JOIN ref_bill_type_stage s ON s.bill_type = c.bill_type AND s.stage_order = 1
 WHERE c.end_stage_1_date IS NOT NULL
 ORDER BY c.candidate_id;

-- Rows of a session already on the clean sheet are stamped with the stage
-- record they correspond to.
UPDATE stage_candidate t
   SET promoted_stage_event_id = e.stage_event_id,
       promoted_at             = c.promoted_at
  FROM stage_event e, bill_candidate c
 WHERE e.bill_id = t.candidate_id AND e.stage_order = t.stage_order
   AND c.candidate_id = t.candidate_id;

DO $$
DECLARE n integer; m integer;
BEGIN
  -- As many rows as dates.
  SELECT count(*) INTO n FROM bill_candidate WHERE end_stage_3_date IS NOT NULL;
  SELECT count(*) INTO m FROM stage_candidate WHERE stage_order = 3;
  IF n <> m THEN RAISE EXCEPTION 'Check failed: % passing dates, % moved.', n, m; END IF;
  SELECT count(*) INTO n FROM bill_candidate WHERE end_stage_1_date IS NOT NULL;
  SELECT count(*) INTO m FROM stage_candidate WHERE stage_order = 1;
  IF n <> m THEN RAISE EXCEPTION 'Check failed: % Stage 1 dates, % moved.', n, m; END IF;

  -- Every date arrived on its own line, unchanged, with its source, when it
  -- was read, and its line's review status.
  SELECT count(*) INTO n
    FROM bill_candidate c
   WHERE (c.end_stage_3_date IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM stage_candidate t
             WHERE t.candidate_id = c.candidate_id AND t.stage_order = 3
               AND t.date_completed = c.end_stage_3_date
               AND t.completed AND NOT t.fell_here
               AND t.source = c.source
               AND t.source_ref IS NOT DISTINCT FROM c.source_ref
               AND t.observed_at = c.observed_at
               AND t.review_status = c.review_status))
      OR (c.end_stage_1_date IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM stage_candidate t
             WHERE t.candidate_id = c.candidate_id AND t.stage_order = 1
               AND t.date_completed = c.end_stage_1_date
               AND NOT t.completed AND t.fell_here
               AND t.source = 'official_report'
               AND t.source_ref ~ '^https?://'
               AND t.observed_at = c.official_report_read_on
               AND t.review_status = c.review_status));
  IF n > 0 THEN RAISE EXCEPTION 'Check failed: % date(s) did not arrive unchanged.', n; END IF;

  -- Every row has its stage's name.
  SELECT count(*) INTO n FROM stage_candidate WHERE stage IS NULL;
  IF n > 0 THEN RAISE EXCEPTION 'Check failed: % moved row(s) have no stage name.', n; END IF;

  -- Every stage record on the clean sheet is reproduced, field by field, by the
  -- row stamped with it, and every row of a promoted line is stamped.
  SELECT count(*) INTO n
    FROM stage_event e
   WHERE NOT EXISTS (
     SELECT 1 FROM stage_candidate t
      WHERE t.promoted_stage_event_id = e.stage_event_id
        AND t.candidate_id   = e.bill_id
        AND t.stage          = e.stage
        AND t.stage_order    = e.stage_order
        AND t.date_completed IS NOT DISTINCT FROM e.date_completed
        AND t.completed      = e.completed
        AND t.fell_here      = e.fell_here
        AND t.source         = e.source
        AND t.source_ref     IS NOT DISTINCT FROM e.source_ref
        AND t.observed_at    = e.observed_at
        AND t.note           IS NOT DISTINCT FROM e.note);
  IF n > 0 THEN RAISE EXCEPTION 'Check failed: % stage record(s) on the clean sheet are not reproduced by the moved rows.', n; END IF;

  SELECT count(*) INTO n
    FROM stage_candidate t JOIN bill_candidate c USING (candidate_id)
   WHERE (c.promoted_bill_id IS NOT NULL) <> (t.promoted_stage_event_id IS NOT NULL);
  IF n > 0 THEN RAISE EXCEPTION 'Check failed: % moved row(s) stamped wrongly for whether their bill is on the clean sheet.', n; END IF;

  RAISE NOTICE 'Moved % passing dates and % Stage 1 rejection dates.',
    (SELECT count(*) FROM stage_candidate WHERE stage_order = 3),
    (SELECT count(*) FROM stage_candidate WHERE stage_order = 1);
END $$;

-- ---------------------------------------------------------------------------
-- 4. The clean sheet: a stage completed on a date not known says why
-- ---------------------------------------------------------------------------

ALTER TABLE stage_event
  ADD CONSTRAINT stage_event_undated_completion_has_a_note
  CHECK (NOT completed OR date_completed IS NOT NULL OR nullif(btrim(note), '') IS NOT NULL);

COMMENT ON TABLE stage_event IS
 'One row per stage a bill actually reached, under that stage''s real name for that kind of bill: Stage 1, 2 and 3 for public and Hybrid Bills, Preliminary, Consideration and Final Stage for Private Bills, then Reconsideration where it happened. A bill rejected at Stage 1 has one row, not three. Written by promotion from the accepted rows of stage_candidate, one row per stage, and removed when the session is taken back off; the rows are renumbered each time. Each row carries its own source.';
COMMENT ON COLUMN stage_event.date_completed IS
 'The date the stage was completed, at the points methodology note M2 sets out: Stage 1 on the Stage 1 debate, Stage 2 at the meeting at which the last amendments were disposed of, Stage 3 on the vote to pass, and the equivalent points for a Private Bill. On a stage the bill did not complete, the date of the decision that ended it where there was one, such as a Stage 1 rejection, and otherwise empty. On a completed stage, empty means completed on a date not known, and the database then requires a note saying why.';
COMMENT ON COLUMN stage_event.note IS
 'Free text for anything irregular about this stage, carried from stage_candidate.note. Required where a stage was completed on a date not known, to say why; the database refuses such a row without one. Empty means nothing irregular.';
COMMENT ON COLUMN stage_event.source IS
 'Where this stage date came from. Allowed values are in ref_source. Where more than one source gave the same stage, this is the more primary of them: the Official Report, then a factsheet, then the PhD dataset. The others stay on stage_candidate.';

-- ---------------------------------------------------------------------------
-- 5. The error checker
-- ---------------------------------------------------------------------------
--
-- The checks on a line are as before, except that the ones about its dates
-- now read the stage-dates sheet. Every row on that sheet not rejected at
-- review is checked too. A problem with a stage names the stage and its source,
-- and gives the row's number in the new last column, stage_candidate_id.
--
-- Contradictions only. A missing date is a gap, listed by v_stage_date_gaps,
-- and does not stop promotion. The exception is a passed bill with no passing
-- date, which was a problem before and still is: every factsheet prints one.

CREATE OR REPLACE VIEW v_candidate_problems AS
WITH stage_rows AS (
    SELECT t.*,
           c.session_number, c.short_title, c.bill_type, c.outcome,
           c.date_introduced, c.date_royal_assent, c.date_concluded,
           coalesce(rs.label, t.stage,
                    'The stage at position ' || coalesce(t.stage_order::text, '?')) AS stage_label
      FROM stage_candidate t
      JOIN bill_candidate c USING (candidate_id)
      LEFT JOIN ref_stage rs ON rs.code = t.stage
     WHERE t.review_status <> 'rejected'
),
line_checks AS (
    SELECT c.candidate_id, c.session_number, c.short_title, c.review_status, p.problem,
           NULL::integer AS stage_candidate_id
    FROM bill_candidate c
    LEFT JOIN session s ON s.session_number = c.session_number
    LEFT JOIN LATERAL (
        SELECT max(r.date_completed) FILTER (WHERE r.stage_order = 3 AND r.completed) AS passed_on
          FROM stage_rows r WHERE r.candidate_id = c.candidate_id
    ) f ON true
    CROSS JOIN LATERAL (VALUES
        (CASE WHEN c.short_title IS NULL OR btrim(c.short_title) = ''
              THEN 'short_title is empty' END),
        (CASE WHEN c.session_number IS NULL
              THEN 'session_number is null' END),
        (CASE WHEN c.session_number IS NOT NULL AND s.session_number IS NULL
              THEN 'session_number '||c.session_number||' has no session row' END),
        (CASE WHEN c.bill_type IS NULL THEN 'bill_type not proposed'
              WHEN NOT EXISTS (SELECT 1 FROM ref_bill_type r WHERE r.code = c.bill_type)
              THEN 'bill_type '||quote_literal(c.bill_type)||' is not in ref_bill_type' END),
        (CASE WHEN c.procedure IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM ref_procedure r WHERE r.code = c.procedure)
              THEN 'procedure '||quote_literal(c.procedure)||' is not in ref_procedure' END),
        (CASE WHEN c.outcome IS NULL THEN 'outcome not proposed — needs a judgement'
              WHEN NOT EXISTS (SELECT 1 FROM ref_outcome r WHERE r.code = c.outcome)
              THEN 'outcome '||quote_literal(c.outcome)||' is not in ref_outcome' END),
        (CASE WHEN c.enactment_status IS NULL THEN 'enactment_status not proposed'
              WHEN NOT EXISTS (SELECT 1 FROM ref_enactment_status r
                               WHERE r.code = c.enactment_status)
              THEN 'enactment_status '||quote_literal(c.enactment_status)
                   ||' is not in ref_enactment_status' END),
        (CASE WHEN c.source IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM ref_source r WHERE r.code = c.source)
              THEN 'source '||quote_literal(c.source)||' is not in ref_source' END),
        (CASE WHEN c.date_concluded IS NOT NULL AND c.date_introduced IS NOT NULL
               AND c.date_concluded < c.date_introduced
              THEN 'concluded before it was introduced' END),
        (CASE WHEN c.raw_date_introduced IS NOT NULL AND c.date_introduced IS NULL
              THEN 'date_introduced unparsed: '||quote_literal(c.raw_date_introduced) END),
        (CASE WHEN c.raw_date_royal_assent IS NOT NULL AND c.date_royal_assent IS NULL
              THEN 'royal assent unparsed: '||quote_literal(c.raw_date_royal_assent) END),
        (CASE WHEN c.raw_date_final IS NOT NULL
               AND f.passed_on IS NULL AND c.date_concluded IS NULL
              THEN 'final date unparsed: '||quote_literal(c.raw_date_final) END),
        (CASE WHEN c.enactment_status = 'enacted' AND c.date_royal_assent IS NULL
              THEN 'enacted but no Royal Assent date' END),
        (CASE WHEN c.outcome <> 'passed' AND c.enactment_status = 'enacted'
              THEN 'enacted but outcome is not passed' END),

        -- ---------------------------------- changed at db/020: the rule is now
        -- about enactment, not about passing. A bill that passed and was later
        -- withdrawn is legitimate and needs its withdrawal date.
        (CASE WHEN c.enactment_status = 'enacted' AND c.date_concluded IS NOT NULL
              THEN 'enacted, but date_concluded is set — a bill that received '
                   ||'Royal Assent concluded at Royal Assent; bill''s CHECK '
                   ||'constraint would refuse this row' END),
        (CASE WHEN c.outcome IS NOT NULL AND c.outcome NOT IN ('passed','in_progress')
               AND c.date_concluded IS NULL
              THEN 'did not pass, but has no date_concluded' END),
        -- ---------------------------------- changed at db/033: reads the
        -- stage-dates sheet.
        (CASE WHEN c.outcome = 'passed' AND f.passed_on IS NULL
              THEN 'passed, but has no Stage 3 date' END),

        (CASE WHEN c.bill_type_stated IS NULL THEN 'bill_type_stated not proposed'
              WHEN NOT EXISTS (SELECT 1 FROM ref_bill_type_stated r
                               WHERE r.code = c.bill_type_stated)
              THEN 'bill_type_stated '||quote_literal(c.bill_type_stated)
                   ||' is not in ref_bill_type_stated' END),

        (CASE WHEN c.title_kind IS NOT NULL AND c.title_kind NOT IN ('act','bill')
              THEN 'title_kind '||quote_literal(c.title_kind)||' is not act or bill' END),
        (CASE WHEN c.enactment_status = 'enacted' AND c.title_kind IS DISTINCT FROM 'act'
              THEN 'enacted, but title_kind is not act — see methodology note M3' END),
        (CASE WHEN c.enactment_status IS DISTINCT FROM 'enacted' AND c.title_kind = 'act'
              THEN 'title_kind is act, but the bill was not enacted' END),
        (CASE WHEN c.enactment_status = 'enacted' AND c.asp_number IS NULL
              THEN 'enacted, but no asp_number' END),
        (CASE WHEN c.asp_number IS NOT NULL AND c.date_royal_assent IS NOT NULL
               AND substring(c.asp_number from '^\d{4}')
                   <> to_char(c.date_royal_assent,'YYYY')
              THEN 'asp_number year does not match the year of Royal Assent' END),
        (CASE WHEN c.short_title ~* '\masp\M'
              THEN 'short_title still contains the asp number' END),

        -- ---------------------------------- added at db/028, from Session 2.
        (CASE WHEN c.short_title ~* '\mSP\s*Bill\s*\d'
              THEN 'short_title still contains the SP Bill number' END),
        (CASE WHEN c.short_title ~* '\mintroduced as\M'
              THEN 'short_title still contains a stated introduced title' END),

        -- ---------------------------------- added at db/031: the route to a
        -- Stage 1 rejection, and the date the Official Report was read.
        (CASE WHEN c.stage_1_rejection_route IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM ref_stage_1_rejection_route r
                               WHERE r.code = c.stage_1_rejection_route)
              THEN 'stage_1_rejection_route '||quote_literal(c.stage_1_rejection_route)
                   ||' is not in ref_stage_1_rejection_route' END),
        (CASE WHEN c.outcome = 'rejected_stage_1' AND c.stage_1_rejection_route IS NULL
              THEN 'rejected at Stage 1, but no route to the rejection is recorded' END),
        (CASE WHEN c.stage_1_rejection_route IS NOT NULL
               AND c.outcome IS DISTINCT FROM 'rejected_stage_1'
              THEN 'a route to a Stage 1 rejection is recorded, but the outcome is not '
                   ||'rejected at Stage 1' END),
        (CASE WHEN c.stage_1_rejection_route = 'committee_motion_9_14_18'
               AND c.bill_type IS DISTINCT FROM 'members'
              THEN 'Rule 9.14.18 route recorded on a bill that is not a Member''s Bill' END),
        (CASE WHEN c.stage_1_rejection_route IS NOT NULL
               AND coalesce(c.review_note, '') !~ 'Result as recorded: "[^"]+"'
              THEN 'a route is recorded, but review_note does not quote the Presiding '
                   ||'Officer''s announcement after "Result as recorded:"' END),
        -- A Stage 1 date read from the Official Report now carries its own read
        -- date on the stage-dates sheet (db/033).
        (CASE WHEN (c.stage_1_rejection_route IS NOT NULL
                    OR c.review_note ILIKE 'Outcome from the Official Report%')
               AND c.official_report_read_on IS NULL
              THEN 'something on this line came from the Official Report, but '
                   ||'official_report_read_on is empty' END),

        (CASE WHEN c.raw_section = 'acts' AND c.outcome IS DISTINCT FROM 'passed'
              THEN 'read from the Acts table, but outcome is '
                   ||coalesce(quote_literal(c.outcome),'null') END),
        (CASE WHEN c.raw_section = 'withdrawn' AND c.outcome IS DISTINCT FROM 'withdrawn'
              THEN 'read from the Withdrawn table, but outcome is '
                   ||coalesce(quote_literal(c.outcome),'null') END),
        (CASE WHEN c.raw_section = 'fallen'
               AND c.outcome NOT IN ('fell_dissolution','fell_other','rejected_stage_1',
                                     'rejected_stage_3')
              THEN 'read from the Fallen table, but outcome is '
                   ||coalesce(quote_literal(c.outcome),'null') END),

        -- Dates inside their session. Dormant until session rows carry dates.
        --
        -- KNOWN LIMITATION, recorded rather than papered over: these compare a
        -- candidate's dates against the session of the FACTSHEET it was read
        -- from, which is what bill_candidate.session_number means. For the four
        -- bills that appear in two factsheets the two are not the same, and
        -- these checks will fire on rows that are correct. Session 1 has no
        -- such bill, so nothing is done about it here; it must be handled
        -- before Session 5 is loaded. See docs/FACTSHEET-SURVEY.md §3.
        (CASE WHEN s.date_first_meeting IS NOT NULL AND c.date_introduced IS NOT NULL
               AND c.date_introduced < s.date_first_meeting
              THEN 'introduced before the session began' END),
        (CASE WHEN s.date_dissolution IS NOT NULL AND c.date_introduced IS NOT NULL
               AND c.date_introduced > s.date_dissolution
              THEN 'introduced after the session ended' END),
        (CASE WHEN s.date_dissolution IS NOT NULL AND f.passed_on IS NOT NULL
               AND f.passed_on > s.date_dissolution
              THEN 'passed after the session ended' END),
        (CASE WHEN s.date_dissolution IS NOT NULL AND c.date_concluded IS NOT NULL
               AND c.date_concluded > s.date_dissolution
              THEN 'concluded after the session ended' END)
    ) AS p(problem)
),
stage_checks AS (
    SELECT r.candidate_id, r.session_number, r.short_title, r.review_status,
           r.stage_label || ', from ' || coalesce(r.source, 'no stated source') || ': ' || p.problem
             AS problem,
           r.stage_candidate_id
    FROM stage_rows r
    CROSS JOIN LATERAL (VALUES
        -- What the row is.
        (CASE WHEN r.stage_order IS NULL OR r.stage_order NOT BETWEEN 1 AND 4
              THEN 'position '||coalesce(r.stage_order::text, 'empty')||' is not 1 to 4' END),
        (CASE WHEN r.stage IS NULL THEN 'no stage named'
              WHEN NOT EXISTS (SELECT 1 FROM ref_stage x WHERE x.code = r.stage)
              THEN 'stage '||quote_literal(r.stage)||' is not in ref_stage' END),
        (CASE WHEN r.stage IS NOT NULL AND r.stage_order IS NOT NULL AND r.bill_type IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM ref_bill_type_stage x
                                WHERE x.bill_type = r.bill_type AND x.stage = r.stage
                                  AND x.stage_order = r.stage_order)
              THEN 'not the right stage name for a '||r.bill_type||' bill at position '
                   ||r.stage_order||' — see ref_bill_type_stage' END),
        (CASE WHEN r.source IS NULL THEN 'no source'
              WHEN NOT EXISTS (SELECT 1 FROM ref_source x WHERE x.code = r.source)
              THEN 'source '||quote_literal(r.source)||' is not in ref_source' END),
        (CASE WHEN r.observed_at IS NULL THEN 'when the source was read is not recorded' END),
        (CASE WHEN r.completed IS NULL THEN 'completed is empty' END),
        (CASE WHEN r.fell_here IS NULL THEN 'fell_here is empty' END),

        -- Whether it holds together.
        (CASE WHEN r.completed AND r.fell_here
              THEN 'marked completed, and also as where the bill ended' END),
        (CASE WHEN r.completed AND r.date_completed IS NULL
               AND nullif(btrim(r.note), '') IS NULL
              THEN 'completed on a date not known, but no note says why' END),
        (CASE WHEN r.completed IS FALSE AND r.fell_here IS FALSE AND r.date_completed IS NOT NULL
              THEN 'not completed and not where the bill ended, but dated' END),
        (CASE WHEN r.fell_here AND r.outcome = 'passed'
              THEN 'marked as where the bill ended, but the bill passed' END),
        (CASE WHEN r.fell_here AND r.outcome = 'rejected_stage_1' AND r.stage_order <> 1
              THEN 'marked as where the bill ended, but the bill was rejected at Stage 1' END),
        (CASE WHEN r.fell_here AND r.outcome = 'rejected_stage_3' AND r.stage_order <> 3
              THEN 'marked as where the bill ended, but the bill was rejected at Stage 3' END),
        (CASE WHEN r.completed AND r.stage_order = 3 AND r.outcome IS DISTINCT FROM 'passed'
              THEN 'final stage completed, but the outcome is not passed' END),

        -- Dates in order: introduction, each stage, Royal Assent; and nothing
        -- after the bill concluded.
        (CASE WHEN r.date_completed < r.date_introduced
              THEN 'dated '||r.date_completed||', before the bill was introduced on '
                   ||r.date_introduced END),
        (CASE WHEN r.completed AND r.date_completed > r.date_royal_assent
              THEN 'dated '||r.date_completed||', after Royal Assent on '||r.date_royal_assent END),
        (CASE WHEN r.date_completed > r.date_concluded
              THEN 'dated '||r.date_completed||', after the bill concluded on '||r.date_concluded END),
        (CASE WHEN r.fell_here AND r.outcome IN ('rejected_stage_1', 'rejected_stage_3')
               AND r.date_completed <> r.date_concluded
              THEN 'the decision that ended the bill is dated '||r.date_completed
                   ||', but the bill concluded on '||r.date_concluded END),
        ((SELECT 'dated '||r.date_completed||', before '||e.stage_label||' on '||e.date_completed
            FROM stage_rows e
           WHERE e.candidate_id = r.candidate_id AND e.stage_order < r.stage_order
             AND e.date_completed > r.date_completed
           ORDER BY e.stage_order LIMIT 1)),

        -- Nothing after the stage where the bill ended, or after one it did not
        -- get through.
        ((SELECT 'recorded after '||e.stage_label||', where the bill ended'
            FROM stage_rows e
           WHERE e.candidate_id = r.candidate_id AND e.fell_here
             AND e.stage_order < r.stage_order
           ORDER BY e.stage_order LIMIT 1)),
        ((SELECT 'recorded, but '||e.stage_label||' before it was not completed'
            FROM stage_rows e
           WHERE e.candidate_id = r.candidate_id AND e.completed IS FALSE
             AND e.fell_here IS FALSE AND e.stage_order < r.stage_order
           ORDER BY e.stage_order LIMIT 1)),

        -- Two sources for the same stage must agree.
        ((SELECT 'disagrees with '||coalesce(e.source, 'another row')||', which gives '
                 ||coalesce(e.date_completed::text, 'no date')
                 ||CASE WHEN e.completed THEN ', completed' ELSE ', not completed' END
                 ||CASE WHEN e.fell_here THEN ', where the bill ended' ELSE '' END
            FROM stage_rows e
           WHERE e.candidate_id = r.candidate_id AND e.stage_order = r.stage_order
             AND e.stage_candidate_id <> r.stage_candidate_id
             AND (e.date_completed IS DISTINCT FROM r.date_completed
                  OR e.completed IS DISTINCT FROM r.completed
                  OR e.fell_here IS DISTINCT FROM r.fell_here
                  OR e.stage IS DISTINCT FROM r.stage)
           ORDER BY e.stage_candidate_id LIMIT 1))
    ) AS p(problem)
)
SELECT * FROM line_checks WHERE problem IS NOT NULL
UNION ALL
SELECT * FROM stage_checks WHERE problem IS NOT NULL;

COMMENT ON VIEW v_candidate_problems IS
 'One row per problem with a staging line or a stage-dates row. Empty before promotion, or the promotion will refuse the session. Extended at db/015; amended at db/020, where the date_concluded rule became a rule about enactment rather than about passing; at db/028 it also flags an SP Bill number or a stated introduced title left inside short_title; at db/031 it requires a route for every Stage 1 rejection, the announcement that route rests on, and the date the Official Report was read. At db/033 it reads the stage-dates staging sheet: the date checks moved there, and it checks that stage dates run in order, stage names fit the bill type, nothing comes after the stage a bill ended at, two sources for the same stage agree, and a stage completed on a date not known has a note. A problem with a stage-dates row names the stage and its source, and gives the row in stage_candidate_id. A missing date is not a problem; it is listed in v_stage_date_gaps.';

-- ---------------------------------------------------------------------------
-- 6. The two old columns come off
-- ---------------------------------------------------------------------------

ALTER TABLE bill_candidate DROP COLUMN end_stage_1_date;
ALTER TABLE bill_candidate DROP COLUMN end_stage_3_date;

COMMENT ON TABLE bill_candidate IS
 'One row per line read off a factsheet. This is the staging area: nothing here is treated as fact until it is reviewed and promoted into bill. Rows are kept permanently, including rejected ones, because they are the record of what the source actually said. Read it as three groups of columns: raw_ columns are the factsheet''s own words, the middle group is what we propose, and the review_ columns are the gate. A bill''s stage dates are not held here: they wait on stage_candidate, one row per stage.';

COMMENT ON COLUMN bill_candidate.official_report_read_on IS
 'The date the Official Report was read for this line, for its outcome or its Stage 1 rejection route. Promotion dates the provenance of those facts by this, not by observed_at, which is when the factsheet was read. A stage date read from the Official Report carries its own read date on stage_candidate. Empty means neither came from the Official Report; the error checker requires it whenever one did.';

-- ---------------------------------------------------------------------------
-- 7. The gaps list
-- ---------------------------------------------------------------------------

CREATE VIEW v_stage_date_gaps AS
WITH lines AS (
    SELECT c.candidate_id, c.session_number, c.short_title, c.bill_type, c.outcome
      FROM bill_candidate c
     WHERE c.review_status <> 'rejected'
),
stage_rows AS (
    SELECT t.* FROM stage_candidate t WHERE t.review_status <> 'rejected'
),
ended AS (
    SELECT candidate_id, min(stage_order) AS ended_at
      FROM stage_rows WHERE fell_here GROUP BY candidate_id
),
furthest AS (
    SELECT candidate_id, max(stage_order) AS furthest
      FROM stage_rows GROUP BY candidate_id
),
expected AS (
    -- A bill that passed: each of its three stages.
    SELECT l.*, g.pos
      FROM lines l CROSS JOIN generate_series(1, 3) AS g(pos)
     WHERE l.outcome = 'passed'
    UNION ALL
    -- A bill that ended early: each stage before the one it ended at.
    SELECT l.*, g.pos
      FROM lines l JOIN ended e USING (candidate_id)
     CROSS JOIN LATERAL generate_series(1, e.ended_at - 1) AS g(pos)
     WHERE l.outcome IS DISTINCT FROM 'passed'
    UNION ALL
    -- A bill still in progress: each stage before the furthest recorded.
    SELECT l.*, g.pos
      FROM lines l JOIN furthest f USING (candidate_id)
     CROSS JOIN LATERAL generate_series(1, least(f.furthest, 4) - 1) AS g(pos)
     WHERE l.outcome = 'in_progress'
       AND NOT EXISTS (SELECT 1 FROM ended e WHERE e.candidate_id = l.candidate_id)
)
SELECT x.candidate_id, x.session_number, x.short_title, x.bill_type, x.outcome,
       x.pos AS stage_order, s.stage,
       CASE WHEN d.rows_completed = 0 THEN 'date not yet entered'
            ELSE 'completed, date not known: '||coalesce(d.notes, '(no note)') END AS gap
  FROM expected x
  LEFT JOIN ref_bill_type_stage s ON s.bill_type = x.bill_type AND s.stage_order = x.pos
  CROSS JOIN LATERAL (
      SELECT count(*) AS rows_completed,
             bool_or(t.date_completed IS NOT NULL) AS dated,
             string_agg(t.note, '; ') AS notes
        FROM stage_rows t
       WHERE t.candidate_id = x.candidate_id AND t.stage_order = x.pos AND t.completed
  ) d
 WHERE NOT coalesce(d.dated, false)
UNION ALL
-- A bill that did not pass, with nothing recording where it ended.
SELECT l.candidate_id, l.session_number, l.short_title, l.bill_type, l.outcome,
       NULL, NULL, 'where the bill ended is not recorded'
  FROM lines l
 WHERE l.outcome IS NOT NULL AND l.outcome NOT IN ('passed', 'in_progress')
   AND NOT EXISTS (SELECT 1 FROM ended e WHERE e.candidate_id = l.candidate_id)
ORDER BY 2, 1, 6;

ALTER VIEW v_stage_date_gaps OWNER TO legdata;

COMMENT ON VIEW v_stage_date_gaps IS
 'The gaps to fill in stage dates, read from the staging sheets: one row per missing date. A bill that passed should have a date for each of its three stages, and a bill that ended early a date for each stage before the one it ended at. A stage completed on a date not known is listed with its note, and a bill that did not pass is listed if nothing records where it ended. A gap does not stop promotion (DECISIONS.md, 2026-09-11); a contradiction does, and is in v_candidate_problems instead. Lines and rows rejected at review are left out.';

COMMENT ON VIEW v_bill_stage_dates IS
 'One row per bill with its stage dates as columns. first_stage/second_stage/final_stage name the stage for that bill type — Stage 1 for a public or Hybrid Bill, Preliminary Stage for a Private Bill.';

-- ---------------------------------------------------------------------------
-- 8. Methodology note M2
-- ---------------------------------------------------------------------------

UPDATE methodology_note
   SET body = $m2$Each stage of a bill is treated as completed at a fixed point, the same for every bill. Stage 1 is completed on the date of the Stage 1 debate, at which the Parliament decides whether to agree to the bill's general principles. Stage 2 is completed on the date of the meeting at which the last amendments were disposed of. Every bill has such a meeting: where no amendments are lodged, the committee, or for an emergency bill the Parliament sitting as a committee, still meets and agrees to each section, so Stage 2 always has a date. Stage 3 is completed on the date the Parliament votes to pass the bill. A stage a bill did not get through is recorded as not completed; where a decision ended it, such as a vote not to agree to the general principles at Stage 1, it carries the date of that decision.

Private Bills go through a Preliminary Stage, a Consideration Stage and a Final Stage, and are recorded under those names. The Parliament says of them: "These stages are quite different from the stages of a Government Bill, and they have different names." They are compared with a public bill's stages by their position in the sequence, not treated as the same stages, and are taken as completed at the equivalent points. The Preliminary Stage ends on the debate at which "The Parliament then debates the bill and decides whether it should go on to Consideration Stage, or be rejected." The Consideration Stage ends at the meeting of the Private Bill committee at which the last amendments were disposed of. The Final Stage ends on the vote to pass. Hybrid Bills go through Stage 1, 2 and 3, of which the Parliament says: "In most ways, these stages are the same as the stages of a Government Bill, but in other ways are like the stages of a Private Bill." They are taken as completed at the same points as a public bill. Both quotations are from the Parliament's pages "About Private Bills" and "About Hybrid Bills", read on 11 September 2026. Those pages describe the procedure as it is now.

The date a bill was passed is taken from the Parliament's legislation fact sheets. The dates of Stages 1 and 2 are taken from the dataset compiled for Steven MacGregor, "Does government dominate the legislative process?" (PhD thesis, University of Stirling, 2021), which covers Sessions 1 to 6. They are added one session at a time; a session whose dates have not yet been added has no Stage 1 or Stage 2 dates. For a bill rejected at Stage 1, the date is taken from the Official Report, and the thesis dataset is checked against it.

Where a stage was completed but its date could not be established, it is recorded as completed with no date, and a note says why. Durations are measured between consecutive dated points: introduction, each dated stage, and Royal Assent. A bill without a date for a stage gives no figure for that stage. Instead it gives one interval across it, labelled with the stages at either end: a bill with no Stage 2 date gives a Stage 1 to Stage 3 interval, not a Stage 2 duration.$m2$,
       applies_to = ARRAY['stage_event.stage', 'stage_event.date_completed',
                          'stage_event.completed', 'stage_event.note', 'stage_event.source']
 WHERE code = 'M2';

-- ---------------------------------------------------------------------------
-- Checks
-- ---------------------------------------------------------------------------

DO $$
DECLARE n integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM methodology_note
                  WHERE code = 'M2' AND body LIKE '%last amendments were disposed of%'
                    AND body NOT LIKE '%not yet recorded%') THEN
    RAISE EXCEPTION 'M2 was not rewritten as expected.';
  END IF;

  IF EXISTS (SELECT 1 FROM ref_bill_type_stage
              WHERE bill_type = 'hybrid' AND stage IN ('preliminary', 'consideration', 'final')) THEN
    RAISE EXCEPTION 'Hybrid Bills still have Private Bill stage names.';
  END IF;

  SELECT count(*) INTO n FROM v_candidate_problems;
  IF n > 0 THEN
    RAISE EXCEPTION 'The error checker finds % problem(s) after the move.', n;
  END IF;
END $$;

-- Postico's user can open the new sheet, the gaps list and the error checker.
SET LOCAL ROLE legdata;
SELECT (SELECT count(*) FROM stage_candidate)      AS stage_date_rows,
       (SELECT count(*) FROM v_stage_date_gaps)    AS gaps,
       (SELECT count(*) FROM v_candidate_problems) AS problems,
       (SELECT count(*) FROM ref_bill_type_stage)  AS stage_name_list;
RESET ROLE;

COMMIT;
