-- 035_bill_title_on_stage_dates_sheet.sql
--
-- The owner types stage dates straight into Postico, onto the stage-dates
-- sheet, instead of filling in spreadsheets for a script to load. Settled with
-- the owner on 2026-09-11: DECISIONS.md, "Stage dates are typed into Postico,
-- not loaded from spreadsheets".
--
-- What it does:
--   1. The stage-dates sheet shows each row's bill title, beside the line
--      number, so a row can be found and a wrong line number shows as the
--      wrong title. The title is filled in automatically whenever a row is
--      saved, and follows a title corrected on the factsheet sheet. It is never
--      typed in, and is not carried onto the clean sheet.
--
--      A new column can only be added at the far right, so the sheet is rebuilt
--      with the column in place. Its rows go back with their own numbers and
--      times, numbering carries on where it was, and the error checker and the
--      gaps list, which read the sheet, are remade from their own definitions.
--      Nothing else depends on the sheet: the drops below are not cascaded, so
--      they would refuse if something did.
--   2. A row's "last changed" time no longer moves when only its title is
--      refreshed, or when a save changes nothing.
--   3. Dates typed with slashes are read day first: 05/01/2000 is 5 January
--      2000. Dates are still shown as 2000-01-05. It takes effect from the next
--      connection, so Postico has to reconnect.
--
-- Everything it creates is given to legdata, so Postico can open it.

BEGIN;

-- ---------------------------------------------------------------------------
-- Keep what is rebuilt
-- ---------------------------------------------------------------------------

CREATE TEMP TABLE kept_rows ON COMMIT DROP AS SELECT * FROM stage_candidate;

CREATE TEMP TABLE kept_numbering ON COMMIT DROP AS
SELECT last_value, is_called FROM stage_candidate_stage_candidate_id_seq;

CREATE TEMP TABLE kept_descriptions ON COMMIT DROP AS
SELECT a.attname, col_description(a.attrelid, a.attnum) AS description
  FROM pg_attribute a
 WHERE a.attrelid = 'public.stage_candidate'::regclass AND a.attnum > 0 AND NOT a.attisdropped;

CREATE TEMP TABLE kept_views ON COMMIT DROP AS
SELECT c.relname, pg_get_viewdef(c.oid) AS definition,
       obj_description(c.oid, 'pg_class') AS description
  FROM pg_class c
 WHERE c.oid IN ('public.v_candidate_problems'::regclass, 'public.v_stage_date_gaps'::regclass);

-- What the two views show now, to check they show exactly the same afterwards.
CREATE TEMP TABLE kept_view_rows ON COMMIT DROP AS
SELECT 'v_candidate_problems' AS relname, to_jsonb(p) AS j FROM v_candidate_problems p
UNION ALL
SELECT 'v_stage_date_gaps', to_jsonb(g) FROM v_stage_date_gaps g;

-- ---------------------------------------------------------------------------
-- 1. Rebuild the sheet with the title beside the line number
-- ---------------------------------------------------------------------------

DROP VIEW v_candidate_problems;
DROP VIEW v_stage_date_gaps;
DROP TABLE stage_candidate;

-- As db/033 made it, with short_title added after candidate_id.
CREATE TABLE stage_candidate (
    stage_candidate_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id            integer NOT NULL REFERENCES bill_candidate,
    short_title             text,
    stage                   text,
    stage_order             integer,
    date_completed          date,
    completed               boolean,
    fell_here               boolean,
    source                  text,
    source_ref              text,
    observed_at             date,
    note                    text,
    review_status           text NOT NULL DEFAULT 'new'
                            CHECK (review_status IN ('new', 'accepted', 'rejected', 'held')),
    review_note             text,
    reviewed_at             timestamptz,
    promoted_stage_event_id integer REFERENCES stage_event ON DELETE SET NULL,
    promoted_at             timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (candidate_id, stage_order, source)
);

ALTER TABLE stage_candidate OWNER TO legdata;

-- The title, looked up from the row's line every time the row is saved.
CREATE FUNCTION stage_candidate_fill_title() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.short_title := (SELECT c.short_title FROM bill_candidate c
                       WHERE c.candidate_id = NEW.candidate_id);
  RETURN NEW;
END;
$$;

ALTER FUNCTION stage_candidate_fill_title() OWNER TO legdata;

COMMENT ON FUNCTION stage_candidate_fill_title() IS
 'Fills in stage_candidate.short_title from the row''s staging line whenever a row is added or changed, replacing anything typed there.';

CREATE TRIGGER stage_candidate_fill_title
    BEFORE INSERT OR UPDATE ON stage_candidate
    FOR EACH ROW EXECUTE FUNCTION stage_candidate_fill_title();

-- 2. The "last changed" time moves only when something other than the title
-- changed.
CREATE TRIGGER stage_candidate_touch
    BEFORE UPDATE ON stage_candidate
    FOR EACH ROW
    WHEN ((to_jsonb(OLD) - 'short_title' - 'updated_at')
          IS DISTINCT FROM (to_jsonb(NEW) - 'short_title' - 'updated_at'))
    EXECUTE FUNCTION touch_updated_at();

-- A title corrected on the factsheet sheet reaches the line's stage rows.
CREATE FUNCTION bill_candidate_title_to_stage_rows() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  UPDATE stage_candidate SET short_title = NEW.short_title
   WHERE candidate_id = NEW.candidate_id;
  RETURN NULL;
END;
$$;

ALTER FUNCTION bill_candidate_title_to_stage_rows() OWNER TO legdata;

COMMENT ON FUNCTION bill_candidate_title_to_stage_rows() IS
 'When a staging line''s short_title changes, refreshes the title shown on that line''s rows of stage_candidate.';

CREATE TRIGGER bill_candidate_title_to_stage_rows
    AFTER UPDATE OF short_title ON bill_candidate
    FOR EACH ROW
    WHEN (OLD.short_title IS DISTINCT FROM NEW.short_title)
    EXECUTE FUNCTION bill_candidate_title_to_stage_rows();

-- The rows go back with their own numbers and times. The title fills itself in.
INSERT INTO stage_candidate (
    stage_candidate_id, candidate_id, stage, stage_order, date_completed,
    completed, fell_here, source, source_ref, observed_at, note,
    review_status, review_note, reviewed_at, promoted_stage_event_id,
    promoted_at, created_at, updated_at)
SELECT stage_candidate_id, candidate_id, stage, stage_order, date_completed,
       completed, fell_here, source, source_ref, observed_at, note,
       review_status, review_note, reviewed_at, promoted_stage_event_id,
       promoted_at, created_at, updated_at
  FROM kept_rows
 ORDER BY stage_candidate_id;

-- Numbering carries on where it was, so no row number is ever given out twice.
DO $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('stage_candidate', 'stage_candidate_id'),
                 k.last_value, k.is_called)
     FROM kept_numbering k;
END $$;

-- The error checker and the gaps list, from their own definitions.
DO $$
DECLARE v record;
BEGIN
  FOR v IN SELECT * FROM kept_views ORDER BY relname LOOP
    EXECUTE format('CREATE VIEW public.%I AS %s', v.relname,
                   regexp_replace(v.definition, ';\s*$', ''));
    EXECUTE format('ALTER VIEW public.%I OWNER TO legdata', v.relname);
    EXECUTE format('COMMENT ON VIEW public.%I IS %L', v.relname, v.description);
  END LOOP;
END $$;

-- Every column keeps its description; the title gets one, and two change.
DO $$
DECLARE d record;
BEGIN
  FOR d IN SELECT * FROM kept_descriptions WHERE description IS NOT NULL LOOP
    EXECUTE format('COMMENT ON COLUMN stage_candidate.%I IS %L', d.attname, d.description);
  END LOOP;
END $$;

COMMENT ON TABLE stage_candidate IS
 'The stage-dates staging sheet: one row per stage of a bill, per source, waiting to be checked before it goes onto stage_event. Every stage date arrives here, whatever its source: a factsheet''s passing date when a session is loaded, a date read from the Official Report at review, and the owner''s PhD dates, typed in directly in Postico. Each row belongs to a line of bill_candidate, which is its bill, and shows that line''s title so the row can be recognised. Nothing reaches stage_event except from an accepted row here. Where two accepted rows give the same stage of the same bill, the error checker requires them to agree, and promotion carries the one from the more primary source: the Official Report, then a factsheet, then the PhD dataset. The other stays here as the check. Rows are kept permanently.';

COMMENT ON COLUMN stage_candidate.short_title IS
 'The title of the bill this row belongs to, copied from its staging line''s short_title, so a row can be recognised and a wrong line number shows as the wrong title. Filled in automatically whenever the row is saved, and refreshed when that title is corrected; anything typed here is replaced. Not a fact waiting for review, and not carried onto stage_event. Empty only if the line has no title.';

COMMENT ON COLUMN stage_candidate.updated_at IS
 'When this row was last changed. Set automatically. A refreshed title on its own, or a save that changes nothing, does not count.';

-- ---------------------------------------------------------------------------
-- 3. Dates with slashes are read day first
-- ---------------------------------------------------------------------------

ALTER DATABASE legdata SET "DateStyle" = 'ISO, DMY';

-- ---------------------------------------------------------------------------
-- Checks
-- ---------------------------------------------------------------------------

DO $$
DECLARE n integer; cols text[];
BEGIN
  SELECT count(*) INTO n FROM stage_candidate;
  IF n <> (SELECT count(*) FROM kept_rows) THEN
    RAISE EXCEPTION 'The sheet has % rows, not the % it had.', n, (SELECT count(*) FROM kept_rows);
  END IF;

  SELECT count(*) INTO n
    FROM kept_rows k FULL JOIN stage_candidate t USING (stage_candidate_id)
   WHERE to_jsonb(k) IS DISTINCT FROM (to_jsonb(t) - 'short_title');
  IF n > 0 THEN
    RAISE EXCEPTION '% row(s) came back different in something other than the title.', n;
  END IF;

  SELECT count(*) INTO n
    FROM stage_candidate t JOIN bill_candidate c USING (candidate_id)
   WHERE t.short_title IS DISTINCT FROM c.short_title;
  IF n > 0 THEN RAISE EXCEPTION '% row(s) do not show their line''s title.', n; END IF;

  SELECT array_agg(attname::text ORDER BY attnum) INTO cols
    FROM pg_attribute
   WHERE attrelid = 'public.stage_candidate'::regclass AND attnum > 0 AND NOT attisdropped;
  IF cols[1:3] <> ARRAY['stage_candidate_id', 'candidate_id', 'short_title'] THEN
    RAISE EXCEPTION 'The title is not beside the line number: %', cols;
  END IF;

  SELECT count(*) INTO n FROM (
    (SELECT relname, j FROM kept_view_rows
     EXCEPT ALL
     SELECT 'v_candidate_problems', to_jsonb(p) FROM v_candidate_problems p
     EXCEPT ALL
     SELECT 'v_stage_date_gaps', to_jsonb(g) FROM v_stage_date_gaps g)
    UNION ALL
    (SELECT 'v_candidate_problems', to_jsonb(p) FROM v_candidate_problems p
     UNION ALL
     SELECT 'v_stage_date_gaps', to_jsonb(g) FROM v_stage_date_gaps g
     EXCEPT ALL
     SELECT relname, j FROM kept_view_rows)) x;
  IF n > 0 THEN
    RAISE EXCEPTION 'The error checker or the gaps list shows % row(s) differently.', n;
  END IF;

  IF (SELECT last_value FROM stage_candidate_stage_candidate_id_seq)
     <> (SELECT last_value FROM kept_numbering) THEN
    RAISE EXCEPTION 'Numbering did not carry on where it was.';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_db_role_setting s JOIN pg_database d ON d.oid = s.setdatabase
                  WHERE d.datname = 'legdata' AND s.setrole = 0
                    AND 'DateStyle=ISO, DMY' = ANY (s.setconfig)) THEN
    RAISE EXCEPTION 'The day-first date setting is not stored.';
  END IF;
END $$;

-- Postico's user can open the rebuilt sheet, the gaps list and the error checker.
SET LOCAL ROLE legdata;
SELECT (SELECT count(*) FROM stage_candidate)      AS stage_date_rows,
       (SELECT count(*) FROM v_stage_date_gaps)    AS gaps,
       (SELECT count(*) FROM v_candidate_problems) AS problems;
RESET ROLE;

COMMIT;
