#!/usr/bin/env python3
"""Generate the contents block at the top of docs/DECISIONS.md.

DECISIONS.md is the record of every decision this project has taken, newest
first, and it is over five thousand lines long. Nobody reads five thousand
lines, so a decision already taken gets taken again, differently. This builds a
contents page from the file's own headings so the whole record fits on a screen
or two.

It is an index, not a summary. Every line is a heading copied exactly as it
stands in the file, so the contents cannot say something the entry does not.
That is the same bargain as the data dictionary: generated, therefore incapable
of drifting.

The script writes only between the two markers and refuses to run if they are
not both present, because this file is the one document here that could not be
rebuilt if it were damaged.

Usage:  python3 tools/make_decisions_index.py
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOC = ROOT / 'docs' / 'DECISIONS.md'

START = '<!-- CONTENTS: generated by tools/make_decisions_index.py. Do not edit between the markers. -->'
END = '<!-- END CONTENTS -->'

HEADING = re.compile(r'^## (\d{4}-\d{2}-\d{2}) — (.+)$')


def anchor(heading, seen):
    """The fragment GitHub gives a heading: lowercased, punctuation dropped,
    spaces to hyphens, and a counter appended when two headings collide."""
    a = heading.lower()
    a = ''.join(ch for ch in a if ch.isalnum() or ch in ' -_')
    a = a.strip().replace(' ', '-')
    seen[a] = seen.get(a, -1) + 1
    return a if seen[a] == 0 else f'{a}-{seen[a]}'


def build(lines):
    seen, by_date, order = {}, {}, []
    for line in lines:
        m = HEADING.match(line)
        if not m:
            continue
        date, title = m.group(1), m.group(2)
        frag = anchor(f'{date} — {title}', seen)
        if date not in by_date:
            by_date[date] = []
            order.append(date)
        by_date[date].append((title, frag))

    total = sum(len(v) for v in by_date.values())
    out = [
        START,
        '',
        f'## Contents — {total} decisions over {len(order)} days',
        '',
        'Generated from the headings below by `tools/make_decisions_index.py`.',
        'Every line is a heading exactly as it stands, so this cannot say',
        'something an entry does not. Newest first, as the file is.',
        '',
    ]
    for date in order:
        out.append(f'**{date}**')
        out.append('')
        for title, frag in by_date[date]:
            out.append(f'- [{title}](#{frag})')
        out.append('')
    out.append(END)
    return out, total, len(order)


def main():
    if not DOC.exists():
        sys.exit(f'{DOC} not found')
    lines = DOC.read_text().split('\n')

    starts = [i for i, l in enumerate(lines) if l.strip() == START]
    ends = [i for i, l in enumerate(lines) if l.strip() == END]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        sys.exit(
            'Not generated. docs/DECISIONS.md must contain exactly one of each\n'
            'marker, in order, with the contents between them:\n\n'
            f'  {START}\n  {END}\n\n'
            'Put them where the contents should go — after the opening\n'
            'paragraph, before the first decision — and run this again. This\n'
            'script will not guess where to cut into that file.')

    block, total, days = build(lines[ends[0] + 1:])
    DOC.write_text('\n'.join(lines[:starts[0]] + block + lines[ends[0] + 1:]))
    print(f'wrote the contents of {DOC.relative_to(ROOT)}: '
          f'{total} decisions over {days} days')


if __name__ == '__main__':
    main()
